version: '3.8'

services:
  
  db:
    image: postgres:latest
    container_name: pg-api-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pg-api-db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data  

 
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: workshop-api-app
    environment:
      DB_URL: jdbc:postgresql://db:5432/pg-api-db
      DB_USERNAME: postgres
      DB_PASSWORD: 123456
    ports:
      - "8090:8090"  
    depends_on:
      - db  

volumes:
  postgres_data:  
